name: Build x86

on:
  push:
    branches:
      - master

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x86
    - 
    - name: compile
      run: make 
  
